name: mintx
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  provider: ^3.0.0
  google_maps_flutter: ^1.0.6
  geocoding: ^1.0.5
  url_launcher: ^5.7.10

  http: ^0.12.2


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
